./sint < "Prueba/programa.txt" > "Salida/salida-programa.txt" 2> "Salida/salida-programa_2.txt"
./sint < "Prueba/Prueba-CASE.txt" > "Salida/salida-Prueba-CASE.txt" 2> "Salida/salida-Prueba-CASE_2.txt"
./sint < "Prueba/Prueba-ENUMERADO.txt" > "Salida/salida-Prueba-ENUMERADO.txt" 2> "Salida/salida-Prueba-ENUMERADO_2.txt"
./sint < "Prueba/Prueba-FUNCIONES.txt" > "Salida/salida-Prueba-FUNCIONES.txt" 2> "Salida/salida-Prueba-FUNCIONES_2.txt"
./sint < "Prueba/Prueba-IF.txt" > "Salida/salida-Prueba-IF.txt" 2> "Salida/salida-Prueba-IF_2.txt"
./sint < "Prueba/Prueba-RISTRA.txt" > "Salida/salida-Prueba-RISTRA.txt" 2> "Salida/salida-Prueba-RISTRA_2.txt"
./sint < "Prueba/Prueba-VECTOR.txt" > "Salida/salida-Prueba-VECTOR.txt" 2> "Salida/salida-Prueba-VECTOR_2.txt"
./sint < "Prueba/Prueba-WHILE.txt" > "Salida/salida-Prueba-WHILE.txt" 2> "Salida/salida-Prueba-WHILE_2.txt"
./sint < "Prueba/Prueba-FICHERO.txt" > "Salida/salida-Prueba-FICHERO.txt"